In [2]:
import numpy as np

In [1]:
x = [1,2,3]

In [3]:
np.array(x)

array([1, 2, 3])

In [4]:
y = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(y)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Creating arrays using numpy's built-in functions**

In [6]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**Creating identity matrix**

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Creating random numbers**

**np.random.rand** generates random numbers from a uniform distribution between 0 and 1. It takes one or more arguments to specify the shape of the output array.

In [16]:
np.random.rand(6)

array([0.86347298, 0.20487667, 0.83578694, 0.74574225, 0.22049408,
       0.76473522])

In [19]:
np.random.rand(3,4)

array([[0.33836329, 0.42692443, 0.03953213, 0.34866418],
       [0.71880021, 0.00388725, 0.17085541, 0.50878229],
       [0.8449021 , 0.89766374, 0.69407008, 0.60985326]])

**np.random.randn**, on the other hand, generates random numbers from a standard normal distribution with mean 0 and standard deviation 1. It also takes one or more arguments to specify the shape of the output array.

In [20]:
np.random.randn(4)

array([ 0.42961992, -1.48219967, -0.53530094,  0.88688407])

In [21]:
np.random.randn(3,4)

array([[ 0.76747949, -0.72774847, -0.28867663,  0.73874011],
       [-1.18432939, -0.5210873 , -0.06263626, -1.46594555],
       [ 0.02995717,  0.9236319 , -1.09635673, -0.63384632]])

In [22]:
np.random.randint(0,100,10)    #The last argument is not a step. It specifies the number of outputs.

array([27, 75, 68, 31,  5, 62, 49, 31, 27, 46])

In [23]:
np.random.randint(0,100,5)

array([96, 51, 99, 29, 35])

**Reshaping arrays**

In [26]:
arr1 = np.arange(12)

In [28]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
arr1.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
arr2 = np.random.randint(0,100,25)

In [31]:
arr2

array([21, 89, 41, 48, 71, 31, 12, 23, 43, 21,  9, 52, 76, 76, 22, 99,  8,
        8, 72, 12, 40, 29,  5, 28, 77])

In [38]:
arr2.reshape(5,5)

array([[21, 89, 41, 48, 71],
       [31, 12, 23, 43, 21],
       [ 9, 52, 76, 76, 22],
       [99,  8,  8, 72, 12],
       [40, 29,  5, 28, 77]])

In [32]:
arr2.max()

99

In [33]:
arr2.min()

5

In [34]:
arr2.argmax()    # returns the index of the max num

15

In [39]:
arr2.argmin()

22

In [40]:
arr2.shape

(25,)

In [41]:
arr2.dtype

dtype('int64')

In [43]:
from numpy.random import randint

In [44]:
randint(2,10)

5

**Indexing and Selection**

In [45]:
arr = np.arange(1,10)

In [46]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr[:5]

array([1, 2, 3, 4, 5])

In [48]:
arr[5:]

array([6, 7, 8, 9])

**Copy of an array vs. View of an array**

In [15]:
arr = np.arange(1,11)

In [16]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr[:5] = 100

In [18]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [19]:
arr_copy = arr.copy()

In [20]:
arr_copy[5:] = 99

In [21]:
arr_copy

array([100, 100, 100, 100, 100,  99,  99,  99,  99,  99])

In [22]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

**Signle bracket vs. Double bracket Index**

In [32]:
arr = np.random.randint(0, 10, (3, 3))

In [33]:
arr

array([[2, 6, 3],
       [1, 6, 4],
       [6, 0, 5]])

In [35]:
arr[0][2]

3

In [36]:
arr[0,2]

3

**Matrix Slicing**

In [39]:
arr = np.arange(1,13).reshape(3,4)

In [40]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
arr[:3,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [46]:
arr[:,-2]

array([ 3,  7, 11])

In [51]:
arr[:1,:1]

array([[1]])

In [49]:
arr[:1,1:2]

array([[2]])

In [53]:
arr[:1,2:3]

array([[3]])

In [54]:
arr[1:2,3:4]

array([[8]])

In [57]:
arr[2:3,:1]

array([[9]])

**Conditional Selection**

In [61]:
arr = np.arange(0,11)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
bool_arr = arr > 5

In [65]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [80]:
arr = np.arange(0,12)

In [81]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [82]:
arr[arr>5]

array([ 6,  7,  8,  9, 10, 11])

In [83]:
arr[arr<3]

array([0, 1, 2])

In [84]:
arr = np.arange(1,51).reshape(5,10)

In [85]:
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [86]:
arr[:1,3:8]

array([[4, 5, 6, 7, 8]])

In [87]:
arr[:,7:]

array([[ 8,  9, 10],
       [18, 19, 20],
       [28, 29, 30],
       [38, 39, 40],
       [48, 49, 50]])

In [88]:
arr[arr>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50])

**Numpy Functions**

In [89]:
arr = np.arange(1,11)

In [90]:
arr * arr 

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [91]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [93]:
arr // arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [94]:
arr % arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [95]:
arr * 100

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [96]:
arr - 100

array([-99, -98, -97, -96, -95, -94, -93, -92, -91, -90])

In [97]:
np.max(arr)

10

In [99]:
np.argmax(arr)

9

In [100]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [102]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

https://numpy.org/doc/stable/reference/ufuncs.html